A critical error has ocurred while running the game!
Error type: <class 'AttributeError'>
What happened: 'FileManager' object has no attribute 'load_file'
Where it happened:  file 'd:\Documentos\Programas\C\nundertale\main.py', at line 20Why it happned: Bad coding xD

Full error traceback:
 Traceback (most recent call last):
  File "d:\Documentos\Programas\C\nundertale\main.py", line 20, in main
    initial_lore_level = GameLevel(lore_sprites)
  File "d:\Documentos\Programas\C\nundertale\model\GameLevel.py", line 11, in __init__
    self.load_level_sprites()
  File "d:\Documentos\Programas\C\nundertale\model\GameLevel.py", line 15, in load_level_sprites
    raw = self.file_manager.load_file(sprite)
AttributeError: 'FileManager' object has no attribute 'load_file'
