A critical error has ocurred while running the game!
Error type: <class 'TypeError'>
What happened: 'tuple' object is not callable
Where it happened:  file 'd:\Documentos\Programas\C\nundertale\main.py', at line 20Why it happned: Bad coding xD

Full error traceback:
 Traceback (most recent call last):
  File "d:\Documentos\Programas\C\nundertale\main.py", line 20, in main
    initial_lore_level = GameLevel(lore_sprites)
  File "d:\Documentos\Programas\C\nundertale\model\GameLevel.py", line 11, in __init__
    self.load_level_sprites()
  File "d:\Documentos\Programas\C\nundertale\model\GameLevel.py", line 15, in load_level_sprites
    sprite_data = self.file_manager.load_image(sprite)
  File "d:\Documentos\Programas\C\nundertale\model\FileManager.py", line 37, in load_image
    geometry = rfile.size())
TypeError: 'tuple' object is not callable
